language: ruby

branches:
  only:
    - source

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
  target_branch: master
  fqdn: www.eyalkalderon.com
