# Welcome to my website!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# 1. Site settings
# 2. Search engine optimization settings
# 3. Navigation settings
# 4. Social settings
# 5. Post settings
# 6. Jekyll settings
# 7. Build settings
# 8. Files excluded from builds

# 1. Site settings
title: Eyal Kalderon
email: ebkalderon@gmail.com
description: My awesome website
baseurl: /
url: https://www.eyalkalderon.com

# 2. Search engine optimization settings
author: Eyal Kalderon
lang: en_US
logo: /assets/img/logo.png
social:
  name: Eyal Kalderon
  links:
    - https://github.com/ebkalderon
    - https://keybase.io/ebkalderon
    - https://www.linkedin.com/in/ebkalderon
    - https://www.reddit.com/user/ebkalderon
    - https://www.youtube.com/channel/UCh4Zb52Vv5AfxbEksOD1sDg

# 3. Navigation settings
navigation:
  About: /about/
  Portfolio: /portfolio/
  Blog: /blog/
  Contact: /contact/

# 4. Social settings
socials:
  email: ebkalderon@gmail.com
  github: ebkalderon
  keybase: ebkalderon
  linkedin: ebkalderon
  reddit: ebkalderon
  youtube: UCh4Zb52Vv5AfxbEksOD1sDg

# 5. Post settings
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

# 6. Jekyll settings
sass:
  style: compressed
timezone: America/New_York

# 7. Build settings
markdown: kramdown
remote_theme: ebkalderon/artsy
plugins:
  - jekyll-feed
  - jemoji

# 8. Files excluded from builds
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
