title: Eyal Kalderon
description: 
email: ebkalderon@gmail.com
url: https://www.eyalkalderon.com/

markdown: rdiscount
permalink: pretty
plugins:
  - bootstrap
  - jekyll-autoprefixer
  - jekyll-tidy

autoprefixer:
  browsers:
    - last 2 versions

jekyll_tidy:
  compress_html: false
