name: zola

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Compile resume.tex
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume.tex
        working_directory: resume/
        latexmk_use_lualatex: true
        post_compile: |
          cp ./resume.pdf ../static/
    - name: Build only
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_DIR: .
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_ONLY: true
    - name: Upload preview resume.pdf
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf-preview
        path: static/resume.pdf
        retention-days: 5
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Compile resume.tex
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex
        working_directory: resume/
        latexmk_use_lualatex: true
        post_compile: |
          cp ./resume.pdf ../static/
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
