name: zola

on:
  push:
    branches:
    - source
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/source'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: 'Build only'
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}
        BUILD_ONLY: true
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/source'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: 'Build and deploy'
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}
